### ISSUE TITLE
Which web3.js version is used in this lib at present?

### ISSUE THREAD

**Issue by CaliosD** [trufflesuite/truffle-contract#109]
I imported web3.js 1.0.0-beta and truffle-contract at the same time in my html like below, but only to find an error on line 514 of truffle-contract.js.

```
<script src="lib/web3.js-dist/web3.min.js"></script>
<script src="lib/truffle-contract-dist/truffle-contract.js"></script>
```

Here's the error.

```
self.web3.version.getNetwork is not a function
    at truffle-contract.js:514
    at new Promise (<anonymous>)
    at Function.detectNetwork (truffle-contract.js:505)
    at Function.deployed (truffle-contract.js:453)
    at Object.callback (app.js:93)
    at o (web3.min.js:1)
    at web3.min.js:1
    at XMLHttpRequest.i.onreadystatechange (web3.min.js:1)
```

And... I've just encountered another problem like [this in issue 56](https://github.com/trufflesuite/truffle-contract/issues/56), the "replace `.toBigNumber` with `.utils.toBN`" problem. So, I wonder if it's another version-related issue..

Thanks in advance for any kind of help. :)

**Comment by vzts** [comment]
@CaliosD It should be the latest stable version of web3.js(which is now v0.20.6). Since there were some breaking changes from 1.0.0 in web3.js, guess truffle-contract needs a major update as well in order to support versions of web3.js later than 1.0.0 when the major version release gets official. 

Personally I really hope that new web3.js itself can operate smoothly with the truffle generated contracts through `web3.eth.Contract` since truffle is the widely adopted framework for solidity development, which could obsolete the use for truffle-contract.

**Comment by CaliosD** [comment]
@vzts Thanks for your advice. I finally gave up truffle-contract and returned to `web3.eth.Contract` itself not long after I submitted this issue. As you mentioned, there were some breaking changed in 1.0.0 in web3.js, and that's why I stick to this version. I think I'll just continue using functions provided by web3 officially and come back to truffle-contract some time later. 😄 

Although I still believe it's a nice library. :P I'll close this issue for now.
