### ISSUE TITLE
Add an option to use gas estimation as the default gas amount for a transaction

### ISSUE THREAD

**Issue by LogvinovLeon** [trufflesuite/truffle-contract#25]
Discussion on gitter: https://gitter.im/ConsenSys/truffle?at=59357958e531dbc905b1f306

# Problem
Currently transactions don't have a default gas amount or you could set the default amount on a contract level. I'd like to use estimateGas for a default gas amount.
# Solution
Introduce an option to provide gas as `estimate`
```
MyContract.defaults({gas: “estimate”})
```
In that case every transaction would use the amount of gas provided by estimateGas.

**Comment by LogvinovLeon** [comment]
I can't assign myself to this issue, but I'm working on a PR

**Comment by LogvinovLeon** [comment]
I'm unassigning myself from this. I fixed this for me, but adding this change to truffle-contract would be too big of a refactor taking into account the current architecture. If someone needs this - feel free to work on that. I'd be happy to use it.

**Comment by tcoulter** [comment]
TODO: Consider the effect of making this the default behavior. Will require considerable testing to ensure we don't break existing applications. If the default, would need to be released on a major Truffle release.

**Comment by jooray** [comment]
I think it is a good idea to do this if we allow for a (configurable) buffer. The problem is this: A local node estimates gas, but a mined transaction uses more gas - for example there is another transaction included in the block sooner than our transaction and this transaction affects the gas consumption (for example one more iteration in a for loop).

The user gets an exception and their gas is eaten.

I think it would be great to configure this somehow per function in the framework (if I know the function spends constant time, use constant gas, for some, allow some buffer, ...). I think this should be a configuration option - perhaps in the .json representing the contract, it shouldn't be handled directly in the code.

**Comment by gnidan** [comment]
Update on this: I have gotten lots of questions/complaints lately about problems deploying to mainnet. Most of the issues appear to be related to transaction gas limits, because Truffle currently makes all transactions use a default gas limit that is very close to the mainnet gas limit. This means that most transactions made by `truffle-contract` have a gas limit set much, much higher than their actual gas cost, which then likely get ignored by miners.

My thoughts: we can use `estimateGas` × some constant, maybe 1.5. (I believe this is the buffer @jooray describes). I don't think this would require a major version bump, as @tcoulter has said, because the current default behavior is probably pretty broken already.

This will require a fair amount of validation, especially to find the right constant multiplier for the buffer. Not sure what best practices people have already been following. Next step might be to find a naïve implementation that could be rolled out quickly, before looking for more nuanced approaches.

**Comment by cgewecke** [comment]
For record-keeping / reference: this has been implemented as part of #95.
