### ISSUE TITLE
Error when invalid args are passed to `.new(...)`

### ISSUE THREAD

**Issue by macalinao** [trufflesuite/truffle-contract#69]
Right now, a contract is created with empty arguments if the arguments are invalid. The `.new(...)` method should ensure the provided arguments follow the contract ABI.

**Comment by brianedelman** [comment]
+1

**Comment by cgewecke** [comment]
Hi @macalinao Thanks for opening this - we're tracking this issue now at #82 and a fix should be in the next patch release. We'll just be verifying that the number of arguments is correct, because it's difficult to disambiguate Solidity args in javascript - e.g uint8 and uint16 are hard distinguish from each other.
